services:
  tf-serving:
    image: tensorflow/serving
    ports:
      - 8501:8501
    environment:
      - MODEL_NAME=tomato_model
    volumes:
      - ./tf_models/tomato_model:/models/tomato_model
    command: >
      tensorflow_model_server
      --rest_api_port=8501
      --model_name=tomato_model
      --model_base_path=/models/tomato_model
